name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm ci

    - name: Run linting and type checking
      run: |
        flake8 .
        mypy .
        npm run lint

    - name: Run unit tests
      run: |
        pytest
        npm test

    - name: Build frontend and backend
      run: |
        npm run build
        python manage.py collectstatic --noinput

    - name: Deploy to staging
      if: github.event_name == 'pull_request'
      run: |
        # HUMAN ASSISTANCE NEEDED
        # Add deployment steps to your staging environment here.
        # This might involve using a specific deployment tool or service.
        # Example:
        # - name: Deploy to Heroku
        #   uses: akhileshns/heroku-deploy@v3.12.12
        #   with:
        #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        #     heroku_app_name: "your-app-staging"
        #     heroku_email: "your-email@example.com"